version: '3.8'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '5173:80'
        environment:
            - VITE_SERVER_URL=https://localhost:3030
            - VITE_GOOGLE_CLIENT_ID=701607865903-euidhkf5c3288tf3afpa6m5oniavtt5o.apps.googleusercontent.com
            - NODE_ENV=production
        restart: always
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '8080:443'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=mongodb://admin:bartar20%40CS@localhost:21771
            - ACCESS_TOKEN_SECRET=1793317fb362c47e4f15c4b04a33e2632bdc81298389ae81b48ac7cca26347d4
            - REFRESH_TOKEN_SECRET=de1d80147291d15db4824c6fb01cfcacd5f215af82505c52c113481c4d1e87dd
            - TOKEN_EXPIRATION=1d
            - REFRESH_TOKEN_EXPIRATION=1d
            - CHAT_GPT_API_KEY=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
            - GOOGLE_CLIENT_ID=701607865903-euidhkf5c3288tf3afpa6m5oniavtt5o.apps.googleusercontent.com
        restart: always
