version: '3.8'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '5173:80'
        env_file:
            - /env/client.env
        restart: always
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '8080:443'
        env_file:
            - /env/server.env
        restart: always
