version: '3.8'
services:
    client:
        image: idoakstein/watchit-client:latest
        ports:
            - '5173:80'
        env_file:
            - /env/client.env
        restart: always
    server:
        image: idoakstein/watchit-server:latest
        ports:
            - '8080:443'
        env_file:
            - /env/server.env
        restart: always
