name: Deploy to Server

on:
    push:
        branches:
            - add-cicd

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Images
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/watchit-client ./client
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/watchit-server ./server
                  docker push ${{ secrets.DOCKER_USERNAME }}/watchit-client
                  docker push ${{ secrets.DOCKER_USERNAME }}/watchit-server

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      sudo docker pull ${{ secrets.DOCKER_USERNAME }}/watchit-client
                      sudo docker pull ${{ secrets.DOCKER_USERNAME }}/watchit-server
                      cd /home/st111/WatchIt
                      sudo docker compose down
                      sudo docker compose up -d
