name: Deploy to Server

on:
    push:
        branches:
            - added-cicd

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Images
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/client ./client
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/server ./server
                  docker push ${{ secrets.DOCKER_USERNAME }}/client
                  docker push ${{ secrets.DOCKER_USERNAME }}/server

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/client
                      docker pull ${{ secrets.DOCKER_USERNAME }}/server
                      cd /path/to/your/project
                      docker-compose down
                      docker-compose up -d
