name: Deploy to Server

on:
    push:
        branches:
            - add-cicd

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Images
              run: |
                  docker build -t WatchIt/client ./client
                  docker build -t WatchIt/server ./server
                  docker push WatchIt/client
                  docker push WatchIt/server

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: 4000
                  script: |
                      docker pull WatchIt/client
                      docker pull WatchIt/server
                      cd /home/st111/WatchIt
                      docker-compose down
                      docker-compose up -d
